### ISSUE TITLE
Bug when moving the piece while scoring

### ISSUE THREAD

**Issue by NeuroTypicalCure** [lmiller1990/vue-tetris#1]
![image](https://user-images.githubusercontent.com/5155910/55683624-0b12b600-5942-11e9-8f51-a060f5e02d1d.png)

Not reproducible every time,  seems easier with the "I" shape.

To reproduce:
Basically try mashing the input keys while you're scoring a line until something looks messed up.

**Comment by lmiller1990** [comment]
Hey, thanks for checking out my project and reporting the issue!

I've seen this too. Not sure what causes it. This was one of the first things I ever made, and the codebase is overly complex - it's unlikely I'll bother fixing this one.
